ALTER TYPE "ScheduleType" ADD VALUE IF NOT EXISTS 'ROTATING';

ALTER TABLE IF EXISTS "WorkSchedule"
  ADD COLUMN IF NOT EXISTS "rotationAnchorDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "rotationPattern" JSONB;

