export const GENIO_SENSITIVE_FIELDS = [
  "tinNo",
  "gsisNo",
  "philHealthNo",
  "pagIbigNo",
  "philSysNumber",
  "contactNumber",
  "email",
  "houseNo",
  "street",
  "emergencyContactName",
  "emergencyContactNumber",
] as const;

export const GENIO_FIELD_ALLOWLIST = {
  employee: [
    "id",
    "employeeNo",
    "prefix",
    "firstName",
    "middleName",
    "lastName",
    "suffix",
    "nickname",
    "gender",
    "birthday",
    "age",
    "position",
    "dateHired",
    "latestAppointment",
    "terminateDate",
    "employeeTypeId",
    "eligibilityId",
    "officeId",
    "designationId",
    "isArchived",
    "isHead",
    "isAwardee",
    "salary",
    "salaryGrade",
    "salaryStep",
    "note",
    "maritalStatus",
  ],
  office: ["id", "departmentId", "name", "bioIndexCode"],
  employeeType: ["id", "departmentId", "name", "value"],
  eligibility: ["id", "departmentId", "name", "value", "eligibilityTypes"],
  historySnapshot: [
    "id",
    "departmentId",
    "employeeId",
    "effectiveAt",
    "officeId",
    "employeeTypeId",
    "eligibilityId",
    "position",
    "gender",
    "maritalStatus",
    "isHead",
    "status",
    "source",
    "note",
  ],
  award: ["id", "employeeId", "title", "description", "givenAt", "issuer", "tags"],
  employmentEvent: ["id", "employeeId", "type", "details", "occurredAt"],
  schedule: ["id", "employeeId", "type", "startTime", "endTime", "effectiveFrom", "effectiveTo", "timezone"],
} as const;

export function isSensitiveGenioField(field: string) {
  return GENIO_SENSITIVE_FIELDS.includes(field as (typeof GENIO_SENSITIVE_FIELDS)[number]);
}
